debug: true

telegram:
  api-url: https://api.telegram.org/
  webhook-path: https://2820-46-138-30-102.eu.ngrok.io  # https://api.telegram.org/bot5128213958:AAERMqZfvd5YsTwGRUAnYqsCBHu_2iMR6DM/setWebhook?url=https://4727-46-138-30-102.eu.ngrok.io

yandex:
  api-weather-url: https://api.weather.yandex.ru/v2/informers

dadata:
  geocod-url: https://cleaner.dadata.ru/api/v1/clean/address
